import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import image from "@/public/bg.jpg"
import logo from "@/public/logo.png"
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather forecast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col h-screen w-screen items-start justify-start md:bg-transparent">
          <Image src={image} alt="background image" fill priority className="-z-10 brightness-50 blur-sm invert" />
          {/* <Image src={logo} alt="logo" priority className="-z-9 max-w-24 max-h-24  mt-5 ml-5 scale-110" /> */}
          {children}
        </main>

      </body>
    </html>
  );
}
